apiVersion: v1
kind: Pod
metadata:
  name: liveness-headers
  labels:
    app.kubernetes.io/name: liveness-headers
spec:
  containers:
    - name: web
      image: startkubernetes/app-health:0.1.0
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
          httpHeaders:
            - name: Host
              value: liveness-host
        initialDelaySeconds: 3
        periodSeconds: 1
