apiVersion: v1
kind: Pod
metadata:
  name: readiness
  labels:
    app.kubernetes.io/name: readiness
spec:
  containers:
    - name: web
      image: startkubernetes/app-health:0.1.0
      ports:
        - containerPort: 3000
      readinessProbe:
        httpGet:
          path: /readyz
          port: 3000
        initialDelaySeconds: 3
        periodSeconds: 1
