apiVersion: apps/v1
kind: Deployment
metadata:
  name: just-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: busybox
          command: ["sh", "-c", "sleep 1h"]
