apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app.kubernetes.io/name: hello
  annotations:
    container.apparmor.security.beta.kubernetes.io/hello-container: localhost/apparmor-example-deny-all
spec:
  containers:
    - name: hello-container
      image: busybox
      command: ["sh", "-c", "echo Hello from my container! && sleep 3600"]
