apiVersion: apps/v1
kind: Deployment
metadata:
  name: computations
  labels:
    app.kubernetes.io/name: computations
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: computations
  template:
    metadata:
      labels:
        app.kubernetes.io/name: computations
    spec:
      containers:
        - name: computations
          image: startkubernetes/computations:0.1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: computations
  labels:
    app.kubernetes.io/name: computations
spec:
  selector:
    app.kubernetes.io/name: computations
  ports:
    - port: 8080
