apiVersion: v1
kind: Pod
metadata:
  name: cpu-hog
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        limits:
          cpu: "100"
        requests:
          cpu: "100"
      command: ["stress"]
      args: ["--cpu", "2"]
