kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: computations
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: computations
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
