apiVersion: v1
kind: Pod
metadata:
  name: quota-pod
spec:
  containers:
    - name: quota-pod
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          memory: "100m"
          cpu: "0.1"
