apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    app.kubernetes.io/name: secret-pod
spec:
  containers:
    - name: secret
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: service-auth
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: service-auth
              key: password
