apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  labels:
    app.kubernetes.io/name: config-pod
spec:
  containers:
    - name: config
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      envFrom:
        - prefix: SIMPLE_CONFIG_
          configMapRef:
            name: simple-config
