apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    app.kubernetes.io/name: secret-pod
spec:
  containers:
    - name: secret
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: auth-secret
          mountPath: "/var/secrets"
          readOnly: true
  volumes:
    - name: auth-secret
      secret:
        secretName: service-auth
