apiVersion: v1
kind: Pod
metadata:
  name: hooks-pod
spec:
  containers:
  - name: hooks-pod
    image: kennethreitz/httpbin
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo Hello postStart! > /var/tmp/hello.txt"]
      preStop:
        exec:
          command: ["/bin/sh","-c","sleep 10"]