apiVersion: batch/v1
kind: Job
metadata:
  name: failing-job
spec:
  completions: 3
  activeDeadlineSeconds: 20
  template:
    metadata:
      labels:
        app.kubernetes.io/name: failing-job
    spec:
      restartPolicy: Never
      containers:
        - name: sleep-container
          image: busybox
          args:
            - sleep
            - "60"
