apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: minute-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: minute-cron
        spec:
          restartPolicy: Never
          containers:
            - name: sleep-container
              image: busybox
              args:
                - sleep
                - "10"
